name: agile_cards
description: A set of cards with software development principles

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rating_dialog: ^1.0.0
  launch_review: ^2.0.0

  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.2.0
  google_fonts: ^1.1.0
  # //https://pub.dev/packages/scrollable_positioned_list#-readme-tab-
  flutter_launcher_icons: ^0.7.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/agile1.png"
  android: true


flutter:
  uses-material-design: true
  fonts:
    - family: Amarante     
      fonts:
        - asset: fonts/Amarante_script.ttf
    - family: BadScript     
      fonts:
        - asset: fonts/BadScript.ttf
    - family: DancingScript     
      fonts:
        - asset: fonts/DancingScript.ttf
    - family: Satisfy     
      fonts:
        - asset: fonts/Satisfy.ttf              
    - family: Fondamento     
      fonts:
        - asset: fonts/fondamentoReg.ttf
        - asset: fonts/fondamentoIta.ttf
          style: italic

assets:
# - assets/images/

