// Generated by https://quicktype.io

class ItemData {
  String title;
  String primaryText;
  String secondaryText;
  String description;
  String refIcon;
  String refUrl;
  String type;

  ItemData({
    this.title,
    this.primaryText,
    this.secondaryText,
    this.description,
    this.refIcon,
    this.refUrl,
    this.type,
  });
}
